version: 2
jobs:
  build:
    docker:
      - image: firedrakeproject/firedrake:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
              git submodule init
              git submodule update --remote
      - run: cd /home/firedrake/firedrake/src/firedrake; git pull; git checkout fw/tinyasm
      - run: . /home/firedrake/firedrake/bin/activate; pip3 install -e .; pytest tests
